FROM busybox
COPY code/models/mnl_model.pkl /knowledgeBase/currentSolution_mnl.pkl
COPY code/models/bestmodel8Fix.h5 /knowledgeBase/currentSolution_ann.h5
COPY code/models/mnl_label_encoder.pkl /knowledgeBase/label_encoder.pkl

